# Generated by Django 4.2.17 on 2026-02-03 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='openid',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='WeChat OpenID'),
        ),
    ]
