# Generated by Django 4.2.17 on 2026-02-05 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_userfollow'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='unionid',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='WeChat UnionID'),
        ),
    ]
