# Generated by Django 4.2.17 on 2026-02-11 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_visitorlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='business_content',
            field=models.TextField(blank=True, verbose_name='Business Content'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='job_title',
            field=models.CharField(blank=True, max_length=100, verbose_name='Job Title'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='Phone Number'),
        ),
    ]
