# Generated by Django 3.2.25 on 2026-03-15 11:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_customuser_oa_openid'),
    ]

    operations = [
    ]
