# Generated by Django 4.2.17 on 2026-02-05 03:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_messagereply'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='membermessage',
            options={'ordering': ['-created_at'], 'verbose_name': 'Forum Topic', 'verbose_name_plural': 'Forum'},
        ),
    ]
