# Generated by Django 4.2.17 on 2026-02-12 12:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0005_alter_membermessage_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='privatemessage',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='chat_images/', verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='privatemessage',
            name='content',
            field=models.TextField(blank=True, verbose_name='Content'),
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('MESSAGE', 'New Message'), ('REPLY', 'New Reply'), ('FOLLOW', 'New Follower'), ('SYSTEM', 'System Notification'), ('APPROVAL', 'Listing Approval')], default='SYSTEM', max_length=20, verbose_name='Type')),
                ('title', models.CharField(max_length=200, verbose_name='Title')),
                ('content', models.TextField(verbose_name='Content')),
                ('is_read', models.BooleanField(default=False, verbose_name='Is Read')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('target_url', models.CharField(blank=True, max_length=500, verbose_name='Target URL')),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='triggered_notifications', to=settings.AUTH_USER_MODEL)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Notification',
                'verbose_name_plural': 'Notifications',
                'ordering': ['-created_at'],
            },
        ),
    ]
