# Generated by Django 4.2.17 on 2026-02-12 10:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('market', '0015_shiplisting_contact_count_shiplisting_view_count'),
    ]

    operations = [
        migrations.CreateModel(
            name='VoyageHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('departure_port', models.CharField(max_length=100, verbose_name='Departure Port')),
                ('arrival_port', models.CharField(max_length=100, verbose_name='Arrival Port')),
                ('departure_date', models.DateField(verbose_name='Departure Date')),
                ('arrival_date', models.DateField(blank=True, null=True, verbose_name='Arrival Date')),
                ('cargo_description', models.CharField(blank=True, max_length=200, verbose_name='Cargo')),
                ('quantity', models.FloatField(blank=True, null=True, verbose_name='Quantity (MT)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ship_listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='voyage_history', to='market.shiplisting')),
            ],
            options={
                'ordering': ['-departure_date'],
            },
        ),
        migrations.CreateModel(
            name='ShipExtendedInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('draft_laden', models.FloatField(blank=True, null=True, verbose_name='Laden Draft (m)')),
                ('draft_ballast', models.FloatField(blank=True, null=True, verbose_name='Ballast Draft (m)')),
                ('hatch_size', models.CharField(blank=True, help_text='L x W', max_length=100, verbose_name='Hatch Size')),
                ('hatch_count', models.IntegerField(default=1, verbose_name='Hatch Count')),
                ('main_engine_power', models.CharField(blank=True, max_length=50, verbose_name='Main Engine Power (kW)')),
                ('speed_laden', models.FloatField(blank=True, null=True, verbose_name='Speed Laden (knots)')),
                ('speed_ballast', models.FloatField(blank=True, null=True, verbose_name='Speed Ballast (knots)')),
                ('fuel_consumption_sea', models.FloatField(blank=True, null=True, verbose_name='Fuel Consumption at Sea (t/day)')),
                ('fuel_consumption_port', models.FloatField(blank=True, null=True, verbose_name='Fuel Consumption in Port (t/day)')),
                ('grain_capacity', models.FloatField(blank=True, null=True, verbose_name='Grain Capacity (cbm)')),
                ('bale_capacity', models.FloatField(blank=True, null=True, verbose_name='Bale Capacity (cbm)')),
                ('deck_strength', models.CharField(blank=True, max_length=50, verbose_name='Deck Strength (t/m2)')),
                ('imo_number', models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='IMO Number')),
                ('call_sign', models.CharField(blank=True, max_length=20, verbose_name='Call Sign')),
                ('mmsi', models.CharField(blank=True, max_length=20, verbose_name='MMSI')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ship_listing', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='extended_info', to='market.shiplisting', verbose_name='Related Ship')),
            ],
        ),
    ]
