# Generated by Django 4.2.17 on 2026-02-13 00:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceListing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('title', models.CharField(max_length=200, verbose_name='Service Title')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('service_area', models.CharField(help_text='e.g. Global, China Ports, Shanghai', max_length=200, verbose_name='Service Area')),
                ('price_range', models.CharField(blank=True, help_text='e.g. Negotiable, $100-$500/day', max_length=100, verbose_name='Price Range')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('view_count', models.PositiveIntegerField(default=0, verbose_name='View Count')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='services', to='services.servicecategory', verbose_name='Category')),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to=settings.AUTH_USER_MODEL, verbose_name='Service Provider')),
            ],
            options={
                'verbose_name': 'Service Listing',
                'verbose_name_plural': 'Service Listings',
                'ordering': ['-created_at'],
            },
        ),
    ]
