# Generated by Django 4.2.17 on 2026-02-15 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0004_reviewreport_resolved_at_reviewreport_resolved_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='hidden_by_owner',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='review',
            name='is_pinned',
            field=models.BooleanField(default=False),
        ),
    ]
