# Generated by Django 4.2.17 on 2026-02-15 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0005_review_hidden_by_owner_review_is_pinned'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='flagged_sensitive',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='review',
            name='sensitive_terms',
            field=models.TextField(blank=True),
        ),
    ]
