# Generated by Django 4.2.17 on 2026-02-12 14:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CrewProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('real_name', models.CharField(max_length=50, verbose_name='Real Name')),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], default='M', max_length=1, verbose_name='Gender')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='Birth Date')),
                ('position', models.CharField(help_text='e.g. Captain, Chief Engineer', max_length=50, verbose_name='Target Position')),
                ('years_of_experience', models.PositiveIntegerField(default=0, verbose_name='Years of Experience')),
                ('certificate_number', models.CharField(blank=True, max_length=50, verbose_name='Seafarer Certificate No.')),
                ('status', models.CharField(choices=[('AVAILABLE', 'Available for Hire'), ('ONBOARD', 'On Board / Unavailable')], default='AVAILABLE', max_length=20, verbose_name='Status')),
                ('resume_file', models.FileField(blank=True, null=True, upload_to='resumes/', verbose_name='Resume File')),
                ('bio', models.TextField(blank=True, verbose_name='Bio/Self Introduction')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='crew_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Crew Profile',
                'verbose_name_plural': 'Crew Profiles',
            },
        ),
        migrations.CreateModel(
            name='CompanyProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_license_no', models.CharField(blank=True, max_length=50, verbose_name='Business License No.')),
                ('business_license_img', models.ImageField(blank=True, null=True, upload_to='licenses/', verbose_name='Business License Image')),
                ('address', models.CharField(blank=True, max_length=255, verbose_name='Company Address')),
                ('contact_person', models.CharField(blank=True, max_length=50, verbose_name='Contact Person')),
                ('contact_phone', models.CharField(blank=True, max_length=20, verbose_name='Contact Phone')),
                ('website', models.URLField(blank=True, verbose_name='Website')),
                ('description', models.TextField(blank=True, verbose_name='Company Description')),
                ('verification_status', models.CharField(choices=[('PENDING', 'Pending Review'), ('VERIFIED', 'Verified'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20, verbose_name='Verification Status')),
                ('is_verified', models.BooleanField(default=False, verbose_name='Is Verified')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='company_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Company Profile',
                'verbose_name_plural': 'Company Profiles',
            },
        ),
    ]
