# Generated by Django 6.0.1 on 2026-01-28 12:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ShipListing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('listing_type', models.CharField(choices=[('SELL', 'Sell Ship'), ('BUY', 'Buy Ship'), ('CHARTER_OFFER', 'Charter Offer (Owner)'), ('CHARTER_REQUEST', 'Charter Request (Renter)')], max_length=20, verbose_name='Listing Type')),
                ('ship_category', models.CharField(choices=[('SELF_PROPELLED', 'Self-propelled Deck Barge'), ('NON_SELF_PROPELLED', 'Non-self-propelled Deck Barge')], max_length=20, verbose_name='Ship Category')),
                ('length', models.FloatField(blank=True, null=True, verbose_name='Length (m)')),
                ('width', models.FloatField(blank=True, null=True, verbose_name='Width (m)')),
                ('depth', models.FloatField(blank=True, null=True, verbose_name='Depth (m)')),
                ('dwt', models.FloatField(blank=True, null=True, verbose_name='Deadweight Tonnage (DWT)')),
                ('build_year', models.IntegerField(blank=True, null=True, verbose_name='Year of Build')),
                ('class_society', models.CharField(blank=True, max_length=100, verbose_name='Classification Society')),
                ('flag_state', models.CharField(blank=True, max_length=100, verbose_name='Flag State')),
                ('delivery_area', models.CharField(blank=True, max_length=200, verbose_name='Delivery Area')),
                ('start_time', models.DateField(blank=True, null=True, verbose_name='Start Time')),
                ('contact_info', models.TextField(verbose_name='Contact Information')),
                ('status', models.CharField(choices=[('PENDING', 'Pending Approval'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20, verbose_name='Status')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('admin_notes', models.TextField(blank=True, verbose_name='Admin Notes')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listings', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ListingImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='listing_images/')),
                ('is_schematic', models.BooleanField(default=True, help_text='Is this a placeholder/schematic image?')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='market.shiplisting')),
            ],
        ),
    ]
