# Generated by Django 3.2.25 on 2026-01-29 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0002_marketnews'),
    ]

    operations = [
        migrations.AddField(
            model_name='marketnews',
            name='content_en',
            field=models.TextField(blank=True, verbose_name='Content (English)'),
        ),
        migrations.AddField(
            model_name='marketnews',
            name='title_en',
            field=models.CharField(blank=True, max_length=200, verbose_name='Title (English)'),
        ),
    ]
