# Generated by Django 3.2.25 on 2026-01-29 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0003_auto_20260129_1416'),
    ]

    operations = [
        migrations.AddField(
            model_name='shiplisting',
            name='description',
            field=models.TextField(blank=True, help_text='Additional details about the ship.', verbose_name='Description (Chinese)'),
        ),
        migrations.AddField(
            model_name='shiplisting',
            name='description_en',
            field=models.TextField(blank=True, help_text='English translation of the description.', verbose_name='Description (English)'),
        ),
    ]
