# Generated by Django 4.2.17 on 2026-02-02 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0004_auto_20260129_1417'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shiplisting',
            name='depth',
            field=models.CharField(blank=True, max_length=50, verbose_name='Depth (m)'),
        ),
        migrations.AlterField(
            model_name='shiplisting',
            name='dwt',
            field=models.CharField(blank=True, max_length=50, verbose_name='Deadweight Tonnage (DWT)'),
        ),
        migrations.AlterField(
            model_name='shiplisting',
            name='length',
            field=models.CharField(blank=True, max_length=50, verbose_name='Length (m)'),
        ),
        migrations.AlterField(
            model_name='shiplisting',
            name='width',
            field=models.CharField(blank=True, max_length=50, verbose_name='Width (m)'),
        ),
    ]
