# Generated by Django 4.2.17 on 2026-02-03 08:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0005_alter_shiplisting_depth_alter_shiplisting_dwt_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='marketnews',
            options={'verbose_name': 'Market News'},
        ),
        migrations.CreateModel(
            name='ListingMatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.FloatField(default=0.0, verbose_name='Match Score')),
                ('is_notified', models.BooleanField(default=False, verbose_name='Notified')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('listing_source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches_as_source', to='market.shiplisting')),
                ('listing_target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches_as_target', to='market.shiplisting')),
            ],
            options={
                'verbose_name': 'Listing Match',
                'verbose_name_plural': 'Listing Matches',
                'unique_together': {('listing_source', 'listing_target')},
            },
        ),
    ]
