# Generated by Django 4.2.17 on 2026-02-03 08:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('market', '0006_alter_marketnews_options_listingmatch'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='listingmatch',
            options={'ordering': ['-score', '-created_at']},
        ),
        migrations.AlterField(
            model_name='listingmatch',
            name='is_notified',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='listingmatch',
            name='score',
            field=models.FloatField(default=0.0),
        ),
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorited_by', to='market.shiplisting')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorites', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('user', 'listing')},
            },
        ),
    ]
