# Generated by Django 4.2.17 on 2026-02-05 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0008_alter_favorite_unique_together_favorite_content_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shiplisting',
            name='listing_type',
            field=models.CharField(choices=[('SELL', 'Sell Ship'), ('BUY', 'Buy Ship'), ('CHARTER_OFFER', 'For Lease'), ('CHARTER_REQUEST', 'Lease Wanted')], max_length=20, verbose_name='Listing Type'),
        ),
    ]
