# Generated by Django 4.2.17 on 2026-02-05 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0009_alter_shiplisting_listing_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='marketnews',
            name='original_source',
            field=models.CharField(blank=True, max_length=100, verbose_name='Original Source Name'),
        ),
        migrations.AddField(
            model_name='marketnews',
            name='source_url',
            field=models.URLField(blank=True, null=True, verbose_name='Source URL'),
        ),
    ]
