# Generated by Django 4.2.17 on 2026-02-05 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0010_marketnews_original_source_marketnews_source_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='CrawledShip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_id', models.CharField(max_length=100, unique=True, verbose_name='Source ID')),
                ('source_url', models.URLField(verbose_name='Source URL')),
                ('ship_category', models.CharField(blank=True, max_length=50, verbose_name='Category')),
                ('dwt', models.CharField(blank=True, max_length=50, verbose_name='DWT')),
                ('build_year', models.IntegerField(blank=True, null=True, verbose_name='Build Year')),
                ('width', models.CharField(blank=True, max_length=50, verbose_name='Width')),
                ('length', models.CharField(blank=True, max_length=50, verbose_name='Length')),
                ('depth', models.CharField(blank=True, max_length=50, verbose_name='Depth')),
                ('full_description', models.TextField(verbose_name='Full Description')),
                ('crawled_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Crawled Ship Data',
                'verbose_name_plural': 'Crawled Ship Data Library',
            },
        ),
    ]
