# Generated by Django 4.2.17 on 2026-02-05 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0011_crawledship'),
    ]

    operations = [
        migrations.AddField(
            model_name='crawledship',
            name='source',
            field=models.CharField(default='sol', max_length=50, verbose_name='Source'),
        ),
    ]
