# Generated by Django 4.2.17 on 2026-02-05 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0012_crawledship_source'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyBriefing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='Briefing Content')),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('PUBLISHED', 'Published')], default='DRAFT', max_length=20, verbose_name='Status')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Daily Market Briefing',
                'verbose_name_plural': 'Daily Market Briefings',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CrawledShipEship',
            fields=[
            ],
            options={
                'verbose_name': 'Eship Data',
                'verbose_name_plural': 'Eship Data Library',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('market.crawledship',),
        ),
        migrations.CreateModel(
            name='CrawledShipHorizon',
            fields=[
            ],
            options={
                'verbose_name': 'Horizon Data',
                'verbose_name_plural': 'Horizon Data Library',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('market.crawledship',),
        ),
        migrations.CreateModel(
            name='CrawledShipSOL',
            fields=[
            ],
            options={
                'verbose_name': 'SOL Data',
                'verbose_name_plural': 'SOL Data Library',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('market.crawledship',),
        ),
    ]
