# Generated by Django 4.2.17 on 2026-02-07 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0013_dailybriefing_crawledshipeship_crawledshiphorizon_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='crawledship',
            name='contact_info',
            field=models.TextField(blank=True, help_text='Extracted contact info', verbose_name='Contact Info'),
        ),
        migrations.AddField(
            model_name='crawledship',
            name='images',
            field=models.JSONField(blank=True, default=list, help_text='List of image URLs', verbose_name='Images'),
        ),
        migrations.AddField(
            model_name='crawledship',
            name='remark',
            field=models.TextField(blank=True, help_text='Extracted remark content', verbose_name='Remark'),
        ),
    ]
