# Generated by Django 4.2.17 on 2026-02-09 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0014_crawledship_contact_info_crawledship_images_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shiplisting',
            name='contact_count',
            field=models.IntegerField(default=0, verbose_name='Contact Count'),
        ),
        migrations.AddField(
            model_name='shiplisting',
            name='view_count',
            field=models.IntegerField(default=0, verbose_name='View Count'),
        ),
    ]
