# Generated by Django 4.2.17 on 2026-03-03 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0015_shiplisting_contact_count_shiplisting_view_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='marketnews',
            name='unique_id',
            field=models.CharField(blank=True, editable=False, max_length=30, null=True, unique=True, verbose_name='Unique ID'),
        ),
        migrations.AddField(
            model_name='shiplisting',
            name='unique_id',
            field=models.CharField(blank=True, editable=False, max_length=30, null=True, unique=True, verbose_name='Unique ID'),
        ),
    ]
