# Generated by Django 4.2.17 on 2026-03-03 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0016_marketnews_unique_id_shiplisting_unique_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shiplisting',
            name='unique_id',
            field=models.CharField(blank=True, max_length=30, null=True, unique=True, verbose_name='Unique ID'),
        ),
    ]
