# Generated by Django 4.2.17 on 2026-02-06 06:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CrewListing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], default='M', max_length=1, verbose_name='Gender')),
                ('nationality_type', models.CharField(choices=[('DOMESTIC', 'Chinese Crew'), ('INTERNATIONAL', 'Foreign Crew')], default='DOMESTIC', max_length=20, verbose_name='Crew Type')),
                ('nationality', models.CharField(help_text='e.g. China, Philippines, India', max_length=100, verbose_name='Nationality')),
                ('residence', models.CharField(max_length=255, verbose_name='Residence Address')),
                ('position', models.CharField(help_text='e.g. Captain, Chief Engineer, Able Seaman', max_length=100, verbose_name='Rank/Position')),
                ('total_sea_experience', models.DecimalField(decimal_places=1, max_digits=4, verbose_name='Total Sea Experience (Years)')),
                ('current_rank_experience', models.DecimalField(decimal_places=1, max_digits=4, verbose_name='Experience in Current Rank (Years)')),
                ('cert_number', models.CharField(max_length=100, verbose_name="Seaman's Book / Certificate No.")),
                ('phone', models.CharField(max_length=50, verbose_name='Phone Number')),
                ('email', models.EmailField(max_length=254, verbose_name='Email Address')),
                ('expected_salary', models.CharField(help_text='e.g. 5000 USD/Month', max_length=100, verbose_name='Expected Salary')),
                ('resume', models.TextField(help_text='Describe past ships, ranks, shipping companies, manning agencies, etc.', verbose_name='Resume')),
                ('status', models.CharField(choices=[('AVAILABLE', 'Available'), ('HIRED', 'Hired')], default='AVAILABLE', max_length=20, verbose_name='Status')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='crew_profile', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Crew Listing',
                'verbose_name_plural': 'Crew Listings',
                'ordering': ['-updated_at'],
            },
        ),
    ]
