# Generated by Django 4.2.17 on 2026-02-04 06:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('market', '0008_alter_favorite_unique_together_favorite_content_type_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('INITIATED', 'Initiated'), ('NEGOTIATION', 'Negotiation'), ('DUE_DILIGENCE', 'Due Diligence / Verification'), ('CONTRACT_DRAFTING', 'Contract Drafting'), ('CONTRACT_SIGNED', 'Contract Signed'), ('DEPOSIT_PENDING', 'Deposit Pending'), ('DEPOSIT_PAID', 'Deposit Paid / Locked'), ('CLOSING', 'Closing / Transfer'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='INITIATED', max_length=30)),
                ('price_agreed', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Agreed Price')),
                ('deposit_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Deposit Amount')),
                ('needs_financing', models.BooleanField(default=False, verbose_name='Needs Financing Assistance')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buying_transactions', to=settings.AUTH_USER_MODEL)),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='market.shiplisting')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='selling_transactions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TransactionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=255)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='transactions.transaction')),
            ],
        ),
        migrations.CreateModel(
            name='TransactionDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='transaction_docs/%Y/%m/')),
                ('doc_type', models.CharField(choices=[('OWNERSHIP_CERT', 'Ownership Certificate'), ('ID_CARD', 'Identity Document'), ('CONTRACT_DRAFT', 'Contract Draft'), ('SIGNED_CONTRACT', 'Signed Contract'), ('PAYMENT_PROOF', 'Payment Proof'), ('OTHER', 'Other')], max_length=30)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('is_verified', models.BooleanField(default=False, verbose_name='Verified by Platform')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='transactions.transaction')),
                ('uploader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
