# Generated by Django 4.2.17 on 2026-02-04 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactiondocument',
            name='doc_type',
            field=models.CharField(choices=[('OWNERSHIP_CERT', 'Ownership Certificate'), ('CLASS_CERT', 'Classification Society Certificate'), ('ID_CARD', 'Identity Document'), ('CONTRACT_DRAFT', 'Contract Draft'), ('SIGNED_CONTRACT', 'Signed Contract'), ('PAYMENT_PROOF', 'Payment Proof'), ('OTHER', 'Other')], max_length=30),
        ),
    ]
