# Generated by Django 4.2.17 on 2026-02-04 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0002_alter_transactiondocument_doc_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='buyer_signed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='transaction',
            name='buyer_signed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='seller_signed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='transaction',
            name='seller_signed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='status',
            field=models.CharField(choices=[('INITIATED', 'Initiated - Waiting for Docs'), ('DOCS_REVIEW', 'Docs Submitted - Under Review'), ('CONTRACT_SIGNING', 'Contract Signing'), ('PAYMENT_PENDING', 'Payment Pending'), ('PAYMENT_VERIFIED', 'Payment Verified - Start Transfer'), ('COMPLETED', 'Completed - Funds Released'), ('CANCELLED', 'Cancelled')], default='INITIATED', max_length=30),
        ),
    ]
