# Generated by Django 4.2.17 on 2026-02-05 01:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0009_alter_shiplisting_listing_type'),
        ('transactions', '0004_alter_transactiondocument_doc_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='title',
            field=models.CharField(blank=True, help_text='e.g. Bulk Carrier 5000DWT Sale', max_length=255, verbose_name='Transaction Title'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='listing',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='market.shiplisting'),
        ),
        migrations.AlterField(
            model_name='transactiondocument',
            name='doc_type',
            field=models.CharField(choices=[('SPECIFICATION', 'Ship Specification'), ('OWNERSHIP_CERT', 'Ownership Certificate'), ('CLASS_CERT', 'Classification Society Certificate'), ('ID_CARD', 'Identity Document'), ('CONTRACT_DRAFT', 'Contract Draft'), ('SIGNED_CONTRACT', 'Signed Contract'), ('PAYMENT_PROOF', 'Payment Proof'), ('TRANSFER_PROOF', 'Transfer Proof'), ('OTHER', 'Other')], max_length=30),
        ),
    ]
