# Generated by Django 4.2.17 on 2026-02-05 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0005_transaction_title_alter_transaction_listing_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='buyer_docs_feedback',
            field=models.TextField(blank=True, verbose_name='Buyer Feedback'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='buyer_docs_verified',
            field=models.BooleanField(default=False, verbose_name='Buyer Verified Docs'),
        ),
    ]
