# Generated by Django 4.2.17 on 2026-02-13 02:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('object_id', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('PENDING', 'Pending Quote'), ('QUOTED', 'Quoted'), ('ACCEPTED', 'Accepted'), ('REJECTED', 'Rejected'), ('CLOSED', 'Closed')], default='PENDING', max_length=20, verbose_name='Status')),
                ('subject', models.CharField(blank=True, max_length=200, verbose_name='Subject')),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inquiries_sent', to=settings.AUTH_USER_MODEL, verbose_name='Buyer')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inquiries_received', to=settings.AUTH_USER_MODEL, verbose_name='Seller')),
            ],
            options={
                'verbose_name': 'Inquiry',
                'verbose_name_plural': 'Inquiries',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='InquiryMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('message', models.TextField(verbose_name='Message')),
                ('is_quote', models.BooleanField(default=False, verbose_name='Is Quote')),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Quoted Price')),
                ('currency', models.CharField(default='CNY', max_length=10, verbose_name='Currency')),
                ('valid_until', models.DateField(blank=True, null=True, verbose_name='Valid Until')),
                ('attachment', models.FileField(blank=True, null=True, upload_to='inquiries/attachments/', verbose_name='Attachment')),
                ('inquiry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='inquiries.inquiry', verbose_name='Inquiry')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inquiry_messages', to=settings.AUTH_USER_MODEL, verbose_name='Sender')),
            ],
            options={
                'verbose_name': 'Inquiry Message',
                'verbose_name_plural': 'Inquiry Messages',
                'ordering': ['created_at'],
            },
        ),
    ]
