# Generated by Django 4.2.17 on 2026-02-15 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicelisting',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
    ]
