# Generated by Django 4.2.17 on 2026-02-15 01:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('services', '0003_servicelisting_approval_note_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicelisting',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='service_listings', to=settings.AUTH_USER_MODEL),
        ),
    ]
