# Generated by Django 4.2.17 on 2026-02-16 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0004_servicelisting_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicelisting',
            name='listing_status',
            field=models.CharField(choices=[('DRAFT', '草稿'), ('SUBMITTED', '已提交'), ('APPROVED', '已通过'), ('REJECTED', '已拒绝'), ('OFFLINE', '已下架')], default='DRAFT', max_length=20),
        ),
    ]
