from django.core.management.base import BaseCommand
from tools.models import Port

class Command(BaseCommand):
    help = 'Populates the database with a comprehensive list of global ports'

    def handle(self, *args, **options):
        ports = [
            # --- China - Coastal (North to South) ---
            {"name_en": "Dalian", "name_zh": "大连", "country_en": "China", "country_zh": "中国", "lat": 38.92, "lon": 121.60},
            {"name_en": "Yingkou", "name_zh": "营口", "country_en": "China", "country_zh": "中国", "lat": 40.29, "lon": 122.10},
            {"name_en": "Qinhuangdao", "name_zh": "秦皇岛", "country_en": "China", "country_zh": "中国", "lat": 39.93, "lon": 119.61},
            {"name_en": "Tangshan", "name_zh": "唐山", "country_en": "China", "country_zh": "中国", "lat": 39.23, "lon": 119.01},
            {"name_en": "Tianjin", "name_zh": "天津", "country_en": "China", "country_zh": "中国", "lat": 38.97, "lon": 117.78},
            {"name_en": "Yantai", "name_zh": "烟台", "country_en": "China", "country_zh": "中国", "lat": 37.55, "lon": 121.38},
            {"name_en": "Weihai", "name_zh": "威海", "country_en": "China", "country_zh": "中国", "lat": 37.50, "lon": 122.12},
            {"name_en": "Qingdao", "name_zh": "青岛", "country_en": "China", "country_zh": "中国", "lat": 36.09, "lon": 120.37},
            {"name_en": "Rizhao", "name_zh": "日照", "country_en": "China", "country_zh": "中国", "lat": 35.41, "lon": 119.56},
            {"name_en": "Lianyungang", "name_zh": "连云港", "country_en": "China", "country_zh": "中国", "lat": 34.74, "lon": 119.46},
            {"name_en": "Shanghai", "name_zh": "上海", "country_en": "China", "country_zh": "中国", "lat": 31.23, "lon": 121.47},
            {"name_en": "Ningbo", "name_zh": "宁波", "country_en": "China", "country_zh": "中国", "lat": 29.88, "lon": 121.54},
            {"name_en": "Zhoushan", "name_zh": "舟山", "country_en": "China", "country_zh": "中国", "lat": 30.01, "lon": 122.10},
            {"name_en": "Wenzhou", "name_zh": "温州", "country_en": "China", "country_zh": "中国", "lat": 28.02, "lon": 120.65},
            {"name_en": "Taizhou", "name_zh": "台州", "country_en": "China", "country_zh": "中国", "lat": 28.68, "lon": 121.44},
            {"name_en": "Fuzhou", "name_zh": "福州", "country_en": "China", "country_zh": "中国", "lat": 25.99, "lon": 119.48},
            {"name_en": "Quanzhou", "name_zh": "泉州", "country_en": "China", "country_zh": "中国", "lat": 24.90, "lon": 118.60},
            {"name_en": "Xiamen", "name_zh": "厦门", "country_en": "China", "country_zh": "中国", "lat": 24.49, "lon": 118.07},
            {"name_en": "Shantou", "name_zh": "汕头", "country_en": "China", "country_zh": "中国", "lat": 23.35, "lon": 116.73},
            {"name_en": "Shenzhen", "name_zh": "深圳", "country_en": "China", "country_zh": "中国", "lat": 22.52, "lon": 113.91},
            {"name_en": "Guangzhou", "name_zh": "广州", "country_en": "China", "country_zh": "中国", "lat": 23.09, "lon": 113.48},
            {"name_en": "Zhuhai", "name_zh": "珠海", "country_en": "China", "country_zh": "中国", "lat": 22.20, "lon": 113.30},
            {"name_en": "Zhanjiang", "name_zh": "湛江", "country_en": "China", "country_zh": "中国", "lat": 21.19, "lon": 110.41},
            {"name_en": "Beihai", "name_zh": "北海", "country_en": "China", "country_zh": "中国", "lat": 21.48, "lon": 109.09},
            {"name_en": "Fangcheng", "name_zh": "防城", "country_en": "China", "country_zh": "中国", "lat": 21.61, "lon": 108.34},
            {"name_en": "Qinzhou", "name_zh": "钦州", "country_en": "China", "country_zh": "中国", "lat": 21.73, "lon": 108.62},
            {"name_en": "Haikou", "name_zh": "海口", "country_en": "China", "country_zh": "中国", "lat": 20.03, "lon": 110.28},
            {"name_en": "Yangpu", "name_zh": "洋浦", "country_en": "China", "country_zh": "中国", "lat": 19.73, "lon": 109.20},
            {"name_en": "Sanya", "name_zh": "三亚", "country_en": "China", "country_zh": "中国", "lat": 18.23, "lon": 109.50},
            {"name_en": "Hong Kong", "name_zh": "香港", "country_en": "China", "country_zh": "中国", "lat": 22.31, "lon": 114.16},
            {"name_en": "Kaohsiung", "name_zh": "高雄", "country_en": "Taiwan", "country_zh": "台湾", "lat": 22.62, "lon": 120.29},
            {"name_en": "Keelung", "name_zh": "基隆", "country_en": "Taiwan", "country_zh": "台湾", "lat": 25.13, "lon": 121.74},
            {"name_en": "Taichung", "name_zh": "台中", "country_en": "Taiwan", "country_zh": "台湾", "lat": 24.26, "lon": 120.51},

            # --- China - River (Yangtze & Pearl River) ---
            {"name_en": "Taicang", "name_zh": "太仓", "country_en": "China", "country_zh": "中国", "lat": 31.62, "lon": 121.22},
            {"name_en": "Nantong", "name_zh": "南通", "country_en": "China", "country_zh": "中国", "lat": 32.01, "lon": 120.84},
            {"name_en": "Zhangjiagang", "name_zh": "张家港", "country_en": "China", "country_zh": "中国", "lat": 31.97, "lon": 120.42},
            {"name_en": "Jiangyin", "name_zh": "江阴", "country_en": "China", "country_zh": "中国", "lat": 31.93, "lon": 120.26},
            {"name_en": "Changzhou", "name_zh": "常州", "country_en": "China", "country_zh": "中国", "lat": 31.95, "lon": 120.00},
            {"name_en": "Zhenjiang", "name_zh": "镇江", "country_en": "China", "country_zh": "中国", "lat": 32.20, "lon": 119.46},
            {"name_en": "Nanjing", "name_zh": "南京", "country_en": "China", "country_zh": "中国", "lat": 32.17, "lon": 118.73},
            {"name_en": "Ma'anshan", "name_zh": "马鞍山", "country_en": "China", "country_zh": "中国", "lat": 31.72, "lon": 118.47},
            {"name_en": "Wuhu", "name_zh": "芜湖", "country_en": "China", "country_zh": "中国", "lat": 31.35, "lon": 118.36},
            {"name_en": "Tongling", "name_zh": "铜陵", "country_en": "China", "country_zh": "中国", "lat": 30.94, "lon": 117.78},
            {"name_en": "Anqing", "name_zh": "安庆", "country_en": "China", "country_zh": "中国", "lat": 30.50, "lon": 117.04},
            {"name_en": "Jiujiang", "name_zh": "九江", "country_en": "China", "country_zh": "中国", "lat": 29.73, "lon": 115.98},
            {"name_en": "Wuhan", "name_zh": "武汉", "country_en": "China", "country_zh": "中国", "lat": 30.63, "lon": 114.36},
            {"name_en": "Yueyang", "name_zh": "岳阳", "country_en": "China", "country_zh": "中国", "lat": 29.41, "lon": 113.08},
            {"name_en": "Jingzhou", "name_zh": "荆州", "country_en": "China", "country_zh": "中国", "lat": 30.29, "lon": 112.23},
            {"name_en": "Yichang", "name_zh": "宜昌", "country_en": "China", "country_zh": "中国", "lat": 30.68, "lon": 111.30},
            {"name_en": "Chongqing", "name_zh": "重庆", "country_en": "China", "country_zh": "中国", "lat": 29.56, "lon": 106.56},
            {"name_en": "Luzhou", "name_zh": "泸州", "country_en": "China", "country_zh": "中国", "lat": 28.87, "lon": 105.44},
            {"name_en": "Yibin", "name_zh": "宜宾", "country_en": "China", "country_zh": "中国", "lat": 28.76, "lon": 104.63},

            # --- Southeast Asia ---
            {"name_en": "Singapore", "name_zh": "新加坡", "country_en": "Singapore", "country_zh": "新加坡", "lat": 1.26, "lon": 103.84},
            {"name_en": "Port Klang", "name_zh": "巴生港", "country_en": "Malaysia", "country_zh": "马来西亚", "lat": 2.99, "lon": 101.39},
            {"name_en": "Tanjung Pelepas", "name_zh": "丹戎帕拉帕斯", "country_en": "Malaysia", "country_zh": "马来西亚", "lat": 1.36, "lon": 103.55},
            {"name_en": "Penang", "name_zh": "槟城", "country_en": "Malaysia", "country_zh": "马来西亚", "lat": 5.41, "lon": 100.36},
            {"name_en": "Pasir Gudang", "name_zh": "巴西古当", "country_en": "Malaysia", "country_zh": "马来西亚", "lat": 1.43, "lon": 103.90},
            {"name_en": "Jakarta", "name_zh": "雅加达", "country_en": "Indonesia", "country_zh": "印度尼西亚", "lat": -6.10, "lon": 106.88},
            {"name_en": "Surabaya", "name_zh": "泗水", "country_en": "Indonesia", "country_zh": "印度尼西亚", "lat": -7.19, "lon": 112.73},
            {"name_en": "Belawan", "name_zh": "贝拉湾", "country_en": "Indonesia", "country_zh": "印度尼西亚", "lat": 3.79, "lon": 98.70},
            {"name_en": "Ho Chi Minh City", "name_zh": "胡志明市", "country_en": "Vietnam", "country_zh": "越南", "lat": 10.74, "lon": 106.74},
            {"name_en": "Hai Phong", "name_zh": "海防", "country_en": "Vietnam", "country_zh": "越南", "lat": 20.86, "lon": 106.70},
            {"name_en": "Da Nang", "name_zh": "岘港", "country_en": "Vietnam", "country_zh": "越南", "lat": 16.11, "lon": 108.22},
            {"name_en": "Vung Tau", "name_zh": "头顿", "country_en": "Vietnam", "country_zh": "越南", "lat": 10.39, "lon": 107.05},
            {"name_en": "Laem Chabang", "name_zh": "林查班", "country_en": "Thailand", "country_zh": "泰国", "lat": 13.07, "lon": 100.88},
            {"name_en": "Bangkok", "name_zh": "曼谷", "country_en": "Thailand", "country_zh": "泰国", "lat": 13.70, "lon": 100.58},
            {"name_en": "Manila", "name_zh": "马尼拉", "country_en": "Philippines", "country_zh": "菲律宾", "lat": 14.58, "lon": 120.96},
            {"name_en": "Cebu", "name_zh": "宿务", "country_en": "Philippines", "country_zh": "菲律宾", "lat": 10.30, "lon": 123.91},
            {"name_en": "Davao", "name_zh": "达沃", "country_en": "Philippines", "country_zh": "菲律宾", "lat": 7.09, "lon": 125.64},
            {"name_en": "Yangon", "name_zh": "仰光", "country_en": "Myanmar", "country_zh": "缅甸", "lat": 16.76, "lon": 96.18},
            {"name_en": "Sihanoukville", "name_zh": "西哈努克", "country_en": "Cambodia", "country_zh": "柬埔寨", "lat": 10.64, "lon": 103.50},

            # --- India & South Asia ---
            {"name_en": "Mumbai (JNPT)", "name_zh": "孟买 (JNPT)", "country_en": "India", "country_zh": "印度", "lat": 18.94, "lon": 72.95},
            {"name_en": "Mundra", "name_zh": "蒙德拉", "country_en": "India", "country_zh": "印度", "lat": 22.81, "lon": 69.70},
            {"name_en": "Kandla", "name_zh": "坎德拉", "country_en": "India", "country_zh": "印度", "lat": 22.99, "lon": 70.22},
            {"name_en": "Chennai", "name_zh": "钦奈", "country_en": "India", "country_zh": "印度", "lat": 13.09, "lon": 80.30},
            {"name_en": "Visakhapatnam", "name_zh": "维萨卡帕特南", "country_en": "India", "country_zh": "印度", "lat": 17.69, "lon": 83.29},
            {"name_en": "Kolkata", "name_zh": "加尔各答", "country_en": "India", "country_zh": "印度", "lat": 22.54, "lon": 88.32},
            {"name_en": "Haldia", "name_zh": "哈尔迪亚", "country_en": "India", "country_zh": "印度", "lat": 22.02, "lon": 88.07},
            {"name_en": "Cochin", "name_zh": "科钦", "country_en": "India", "country_zh": "印度", "lat": 9.96, "lon": 76.26},
            {"name_en": "Mangalore", "name_zh": "芒格洛尔", "country_en": "India", "country_zh": "印度", "lat": 12.93, "lon": 74.81},
            {"name_en": "Tuticorin", "name_zh": "杜蒂戈林", "country_en": "India", "country_zh": "印度", "lat": 8.75, "lon": 78.16},
            {"name_en": "Colombo", "name_zh": "科伦坡", "country_en": "Sri Lanka", "country_zh": "斯里兰卡", "lat": 6.94, "lon": 79.84},
            {"name_en": "Chittagong", "name_zh": "吉大港", "country_en": "Bangladesh", "country_zh": "孟加拉国", "lat": 22.31, "lon": 91.80},
            {"name_en": "Karachi", "name_zh": "卡拉奇", "country_en": "Pakistan", "country_zh": "巴基斯坦", "lat": 24.83, "lon": 66.98},

            # --- Middle East (Persian Gulf & Red Sea) ---
            {"name_en": "Jebel Ali", "name_zh": "杰贝阿里", "country_en": "UAE", "country_zh": "阿联酋", "lat": 25.01, "lon": 55.06},
            {"name_en": "Dubai", "name_zh": "迪拜", "country_en": "UAE", "country_zh": "阿联酋", "lat": 25.26, "lon": 55.29},
            {"name_en": "Abu Dhabi", "name_zh": "阿布扎比", "country_en": "UAE", "country_zh": "阿联酋", "lat": 24.51, "lon": 54.38},
            {"name_en": "Sharjah", "name_zh": "沙迦", "country_en": "UAE", "country_zh": "阿联酋", "lat": 25.36, "lon": 55.37},
            {"name_en": "Dammam", "name_zh": "达曼", "country_en": "Saudi Arabia", "country_zh": "沙特阿拉伯", "lat": 26.54, "lon": 50.18},
            {"name_en": "Jubail", "name_zh": "朱拜勒", "country_en": "Saudi Arabia", "country_zh": "沙特阿拉伯", "lat": 27.02, "lon": 49.66},
            {"name_en": "Jeddah", "name_zh": "吉达", "country_en": "Saudi Arabia", "country_zh": "沙特阿拉伯", "lat": 21.47, "lon": 39.16},
            {"name_en": "King Abdullah Port", "name_zh": "阿卜杜拉国王港", "country_en": "Saudi Arabia", "country_zh": "沙特阿拉伯", "lat": 22.54, "lon": 39.06},
            {"name_en": "Hamad Port", "name_zh": "哈马德港", "country_en": "Qatar", "country_zh": "卡塔尔", "lat": 25.00, "lon": 51.60},
            {"name_en": "Doha", "name_zh": "多哈", "country_en": "Qatar", "country_zh": "卡塔尔", "lat": 25.29, "lon": 51.55},
            {"name_en": "Bahrain", "name_zh": "巴林", "country_en": "Bahrain", "country_zh": "巴林", "lat": 26.21, "lon": 50.62},
            {"name_en": "Shuwaikh", "name_zh": "舒韦赫", "country_en": "Kuwait", "country_zh": "科威特", "lat": 29.35, "lon": 47.91},
            {"name_en": "Bandar Abbas", "name_zh": "阿巴斯港", "country_en": "Iran", "country_zh": "伊朗", "lat": 27.14, "lon": 56.06},
            {"name_en": "Sohar", "name_zh": "苏哈尔", "country_en": "Oman", "country_zh": "阿曼", "lat": 24.50, "lon": 56.63},
            {"name_en": "Salalah", "name_zh": "萨拉拉", "country_en": "Oman", "country_zh": "阿曼", "lat": 16.94, "lon": 54.00},

            # --- East Africa ---
            {"name_en": "Mombasa", "name_zh": "蒙巴萨", "country_en": "Kenya", "country_zh": "肯尼亚", "lat": -4.05, "lon": 39.65},
            {"name_en": "Dar es Salaam", "name_zh": "达累斯萨拉姆", "country_en": "Tanzania", "country_zh": "坦桑尼亚", "lat": -6.82, "lon": 39.29},
            {"name_en": "Djibouti", "name_zh": "吉布提", "country_en": "Djibouti", "country_zh": "吉布提", "lat": 11.60, "lon": 43.14},
            {"name_en": "Port Sudan", "name_zh": "苏丹港", "country_en": "Sudan", "country_zh": "苏丹", "lat": 19.61, "lon": 37.22},
            {"name_en": "Maputo", "name_zh": "马普托", "country_en": "Mozambique", "country_zh": "莫桑比克", "lat": -25.97, "lon": 32.56},
            {"name_en": "Beira", "name_zh": "贝拉", "country_en": "Mozambique", "country_zh": "莫桑比克", "lat": -19.82, "lon": 34.83},
            {"name_en": "Toamasina", "name_zh": "图阿马西纳", "country_en": "Madagascar", "country_zh": "马达加斯加", "lat": -18.15, "lon": 49.42},
            {"name_en": "Port Louis", "name_zh": "路易港", "country_en": "Mauritius", "country_zh": "毛里求斯", "lat": -20.15, "lon": 57.49},

            # --- West Africa ---
            {"name_en": "Lagos (Apapa)", "name_zh": "拉各斯 (阿帕帕)", "country_en": "Nigeria", "country_zh": "尼日利亚", "lat": 6.44, "lon": 3.36},
            {"name_en": "Lagos (Tincan)", "name_zh": "拉各斯 (廷坎)", "country_en": "Nigeria", "country_zh": "尼日利亚", "lat": 6.43, "lon": 3.33},
            {"name_en": "Onne", "name_zh": "奥恩", "country_en": "Nigeria", "country_zh": "尼日利亚", "lat": 4.70, "lon": 7.16},
            {"name_en": "Lome", "name_zh": "洛美", "country_en": "Togo", "country_zh": "多哥", "lat": 6.13, "lon": 1.28},
            {"name_en": "Tema", "name_zh": "特马", "country_en": "Ghana", "country_zh": "加纳", "lat": 5.63, "lon": 0.01},
            {"name_en": "Abidjan", "name_zh": "阿比让", "country_en": "Ivory Coast", "country_zh": "科特迪瓦", "lat": 5.25, "lon": -4.01},
            {"name_en": "Dakar", "name_zh": "达喀尔", "country_en": "Senegal", "country_zh": "塞内加尔", "lat": 14.68, "lon": -17.43},
            {"name_en": "Cotonou", "name_zh": "科托努", "country_en": "Benin", "country_zh": "贝宁", "lat": 6.35, "lon": 2.44},
            {"name_en": "Pointe-Noire", "name_zh": "黑角", "country_en": "Congo", "country_zh": "刚果", "lat": -4.79, "lon": 11.83},
            {"name_en": "Luanda", "name_zh": "罗安达", "country_en": "Angola", "country_zh": "安哥拉", "lat": -8.80, "lon": 13.24},
            {"name_en": "Walvis Bay", "name_zh": "鲸湾", "country_en": "Namibia", "country_zh": "纳米比亚", "lat": -22.94, "lon": 14.50},
            {"name_en": "Cape Town", "name_zh": "开普敦", "country_en": "South Africa", "country_zh": "南非", "lat": -33.90, "lon": 18.43},
            {"name_en": "Durban", "name_zh": "德班", "country_en": "South Africa", "country_zh": "南非", "lat": -29.87, "lon": 31.02},
            {"name_en": "Richards Bay", "name_zh": "理查兹湾", "country_en": "South Africa", "country_zh": "南非", "lat": -28.80, "lon": 32.04},

            # --- Europe ---
            {"name_en": "Rotterdam", "name_zh": "鹿特丹", "country_en": "Netherlands", "country_zh": "荷兰", "lat": 51.95, "lon": 4.14},
            {"name_en": "Antwerp", "name_zh": "安特卫普", "country_en": "Belgium", "country_zh": "比利时", "lat": 51.27, "lon": 4.34},
            {"name_en": "Hamburg", "name_zh": "汉堡", "country_en": "Germany", "country_zh": "德国", "lat": 53.53, "lon": 9.94},
            {"name_en": "Bremerhaven", "name_zh": "不来梅哈芬", "country_en": "Germany", "country_zh": "德国", "lat": 53.56, "lon": 8.56},
            {"name_en": "London Gateway", "name_zh": "伦敦门户港", "country_en": "UK", "country_zh": "英国", "lat": 51.50, "lon": 0.49},
            {"name_en": "Felixstowe", "name_zh": "费利克斯托", "country_en": "UK", "country_zh": "英国", "lat": 51.95, "lon": 1.31},
            {"name_en": "Southampton", "name_zh": "南安普顿", "country_en": "UK", "country_zh": "英国", "lat": 50.89, "lon": -1.41},
            {"name_en": "Le Havre", "name_zh": "勒阿弗尔", "country_en": "France", "country_zh": "法国", "lat": 49.48, "lon": 0.13},
            {"name_en": "Marseille", "name_zh": "马赛", "country_en": "France", "country_zh": "法国", "lat": 43.34, "lon": 5.34},
            {"name_en": "Valencia", "name_zh": "瓦伦西亚", "country_en": "Spain", "country_zh": "西班牙", "lat": 39.44, "lon": -0.32},
            {"name_en": "Algeciras", "name_zh": "阿尔赫西拉斯", "country_en": "Spain", "country_zh": "西班牙", "lat": 36.13, "lon": -5.43},
            {"name_en": "Barcelona", "name_zh": "巴塞罗那", "country_en": "Spain", "country_zh": "西班牙", "lat": 41.34, "lon": 2.16},
            {"name_en": "Genoa", "name_zh": "热那亚", "country_en": "Italy", "country_zh": "意大利", "lat": 44.40, "lon": 8.91},
            {"name_en": "Gioia Tauro", "name_zh": "焦亚陶罗", "country_en": "Italy", "country_zh": "意大利", "lat": 38.44, "lon": 15.90},
            {"name_en": "Piraeus", "name_zh": "比雷埃夫斯", "country_en": "Greece", "country_zh": "希腊", "lat": 37.94, "lon": 23.62},
            {"name_en": "Marsaxlokk", "name_zh": "马尔萨什洛克", "country_en": "Malta", "country_zh": "马耳他", "lat": 35.83, "lon": 14.54},
            {"name_en": "St. Petersburg", "name_zh": "圣彼得堡", "country_en": "Russia", "country_zh": "俄罗斯", "lat": 59.88, "lon": 30.22},
            {"name_en": "Novorossiysk", "name_zh": "新罗西斯克", "country_en": "Russia", "country_zh": "俄罗斯", "lat": 44.72, "lon": 37.79},
            {"name_en": "Gdansk", "name_zh": "格但斯克", "country_en": "Poland", "country_zh": "波兰", "lat": 54.40, "lon": 18.67},

            # --- Oceania (Australia, New Zealand, Pacific Islands) ---
            {"name_en": "Sydney", "name_zh": "悉尼", "country_en": "Australia", "country_zh": "澳大利亚", "lat": -33.85, "lon": 151.21},
            {"name_en": "Melbourne", "name_zh": "墨尔本", "country_en": "Australia", "country_zh": "澳大利亚", "lat": -37.84, "lon": 144.93},
            {"name_en": "Brisbane", "name_zh": "布里斯班", "country_en": "Australia", "country_zh": "澳大利亚", "lat": -27.38, "lon": 153.17},
            {"name_en": "Fremantle", "name_zh": "弗里曼特尔", "country_en": "Australia", "country_zh": "澳大利亚", "lat": -32.05, "lon": 115.74},
            {"name_en": "Port Hedland", "name_zh": "黑德兰港", "country_en": "Australia", "country_zh": "澳大利亚", "lat": -20.31, "lon": 118.59},
            {"name_en": "Dampier", "name_zh": "丹皮尔", "country_en": "Australia", "country_zh": "澳大利亚", "lat": -20.66, "lon": 116.71},
            {"name_en": "Newcastle", "name_zh": "纽卡斯尔", "country_en": "Australia", "country_zh": "澳大利亚", "lat": -32.92, "lon": 151.78},
            {"name_en": "Gladstone", "name_zh": "格拉德斯通", "country_en": "Australia", "country_zh": "澳大利亚", "lat": -23.83, "lon": 151.26},
            {"name_en": "Darwin", "name_zh": "达尔文", "country_en": "Australia", "country_zh": "澳大利亚", "lat": -12.47, "lon": 130.84},
            {"name_en": "Auckland", "name_zh": "奥克兰", "country_en": "New Zealand", "country_zh": "新西兰", "lat": -36.84, "lon": 174.78},
            {"name_en": "Tauranga", "name_zh": "陶朗加", "country_en": "New Zealand", "country_zh": "新西兰", "lat": -37.66, "lon": 176.18},
            {"name_en": "Wellington", "name_zh": "惠灵顿", "country_en": "New Zealand", "country_zh": "新西兰", "lat": -41.28, "lon": 174.78},
            {"name_en": "Lyttelton", "name_zh": "利特尔顿", "country_en": "New Zealand", "country_zh": "新西兰", "lat": -43.60, "lon": 172.71},
            {"name_en": "Suva", "name_zh": "苏瓦", "country_en": "Fiji", "country_zh": "斐济", "lat": -18.13, "lon": 178.43},
            {"name_en": "Lautoka", "name_zh": "劳托卡", "country_en": "Fiji", "country_zh": "斐济", "lat": -17.61, "lon": 177.44},
            {"name_en": "Port Moresby", "name_zh": "莫尔兹比港", "country_en": "Papua New Guinea", "country_zh": "巴布亚新几内亚", "lat": -9.47, "lon": 147.14},
            {"name_en": "Lae", "name_zh": "莱城", "country_en": "Papua New Guinea", "country_zh": "巴布亚新几内亚", "lat": -6.73, "lon": 147.00},
            {"name_en": "Noumea", "name_zh": "努美阿", "country_en": "New Caledonia", "country_zh": "新喀里多尼亚", "lat": -22.27, "lon": 166.44},
            {"name_en": "Apia", "name_zh": "阿皮亚", "country_en": "Samoa", "country_zh": "萨摩亚", "lat": -13.83, "lon": -171.76},
            {"name_en": "Honiara", "name_zh": "霍尼亚拉", "country_en": "Solomon Islands", "country_zh": "所罗门群岛", "lat": -9.42, "lon": 159.96},
            {"name_en": "Port Vila", "name_zh": "维拉港", "country_en": "Vanuatu", "country_zh": "瓦努阿图", "lat": -17.74, "lon": 168.31},
            {"name_en": "Nuku'alofa", "name_zh": "努库阿洛法", "country_en": "Tonga", "country_zh": "汤加", "lat": -21.13, "lon": -175.18},
            {"name_en": "Papeete", "name_zh": "帕皮提", "country_en": "French Polynesia", "country_zh": "法属波利尼西亚", "lat": -17.53, "lon": -149.57},
            {"name_en": "Male", "name_zh": "马累", "country_en": "Maldives", "country_zh": "马尔代夫", "lat": 4.17, "lon": 73.51},


            # --- North America ---
            {"name_en": "Los Angeles", "name_zh": "洛杉矶", "country_en": "USA", "country_zh": "美国", "lat": 33.73, "lon": -118.26},
            {"name_en": "Long Beach", "name_zh": "长滩", "country_en": "USA", "country_zh": "美国", "lat": 33.75, "lon": -118.21},
            {"name_en": "New York", "name_zh": "纽约", "country_en": "USA", "country_zh": "美国", "lat": 40.66, "lon": -74.03},
            {"name_en": "New Jersey", "name_zh": "新泽西", "country_en": "USA", "country_zh": "美国", "lat": 40.68, "lon": -74.15},
            {"name_en": "Savannah", "name_zh": "萨凡纳", "country_en": "USA", "country_zh": "美国", "lat": 32.08, "lon": -81.08},
            {"name_en": "Houston", "name_zh": "休斯敦", "country_en": "USA", "country_zh": "美国", "lat": 29.72, "lon": -95.03},
            {"name_en": "Norfolk", "name_zh": "诺福克", "country_en": "USA", "country_zh": "美国", "lat": 36.93, "lon": -76.32},
            {"name_en": "Seattle", "name_zh": "西雅图", "country_en": "USA", "country_zh": "美国", "lat": 47.58, "lon": -122.36},
            {"name_en": "Tacoma", "name_zh": "塔科马", "country_en": "USA", "country_zh": "美国", "lat": 47.27, "lon": -122.41},
            {"name_en": "Charleston", "name_zh": "查尔斯顿", "country_en": "USA", "country_zh": "美国", "lat": 32.78, "lon": -79.92},
            {"name_en": "Miami", "name_zh": "迈阿密", "country_en": "USA", "country_zh": "美国", "lat": 25.77, "lon": -80.17},
            {"name_en": "Vancouver", "name_zh": "温哥华", "country_en": "Canada", "country_zh": "加拿大", "lat": 49.30, "lon": -123.08},
            {"name_en": "Prince Rupert", "name_zh": "鲁珀特王子港", "country_en": "Canada", "country_zh": "加拿大", "lat": 54.30, "lon": -130.33},
            {"name_en": "Montreal", "name_zh": "蒙特利尔", "country_en": "Canada", "country_zh": "加拿大", "lat": 45.54, "lon": -73.53},
            {"name_en": "Manzanillo (MX)", "name_zh": "曼萨尼约 (墨西哥)", "country_en": "Mexico", "country_zh": "墨西哥", "lat": 19.07, "lon": -104.30},
            {"name_en": "Lazaro Cardenas", "name_zh": "拉萨罗卡德纳斯", "country_en": "Mexico", "country_zh": "墨西哥", "lat": 17.94, "lon": -102.17},
            {"name_en": "Veracruz", "name_zh": "韦拉克鲁斯", "country_en": "Mexico", "country_zh": "墨西哥", "lat": 19.20, "lon": -96.13},

            # --- Central & South America ---
            {"name_en": "Colon", "name_zh": "科隆", "country_en": "Panama", "country_zh": "巴拿马", "lat": 9.36, "lon": -79.88},
            {"name_en": "Balboa", "name_zh": "巴尔博亚", "country_en": "Panama", "country_zh": "巴拿马", "lat": 8.95, "lon": -79.56},
            {"name_en": "Santos", "name_zh": "桑托斯", "country_en": "Brazil", "country_zh": "巴西", "lat": -23.97, "lon": -46.30},
            {"name_en": "Paranagua", "name_zh": "帕拉那瓜", "country_en": "Brazil", "country_zh": "巴西", "lat": -25.50, "lon": -48.50},
            {"name_en": "Rio de Janeiro", "name_zh": "里约热内卢", "country_en": "Brazil", "country_zh": "巴西", "lat": -22.88, "lon": -43.19},
            {"name_en": "Itajai", "name_zh": "伊塔雅伊", "country_en": "Brazil", "country_zh": "巴西", "lat": -26.90, "lon": -48.65},
            {"name_en": "Buenos Aires", "name_zh": "布宜诺斯艾利斯", "country_en": "Argentina", "country_zh": "阿根廷", "lat": -34.58, "lon": -58.37},
            {"name_en": "Montevideo", "name_zh": "蒙得维的亚", "country_en": "Uruguay", "country_zh": "乌拉圭", "lat": -34.90, "lon": -56.21},
            {"name_en": "Callao", "name_zh": "卡亚俄", "country_en": "Peru", "country_zh": "秘鲁", "lat": -12.04, "lon": -77.15},
            {"name_en": "San Antonio", "name_zh": "圣安东尼奥", "country_en": "Chile", "country_zh": "智利", "lat": -33.58, "lon": -71.62},
            {"name_en": "Valparaiso", "name_zh": "瓦尔帕莱索", "country_en": "Chile", "country_zh": "智利", "lat": -33.03, "lon": -71.62},
            {"name_en": "Guayaquil", "name_zh": "瓜亚基尔", "country_en": "Ecuador", "country_zh": "厄瓜多尔", "lat": -2.28, "lon": -79.90},
            {"name_en": "Buenaventura", "name_zh": "布埃纳文图拉", "country_en": "Colombia", "country_zh": "哥伦比亚", "lat": 3.87, "lon": -77.06},
            {"name_en": "Cartagena", "name_zh": "卡塔赫纳", "country_en": "Colombia", "country_zh": "哥伦比亚", "lat": 10.39, "lon": -75.52},
            {"name_en": "Kingston", "name_zh": "金斯敦", "country_en": "Jamaica", "country_zh": "牙买加", "lat": 17.96, "lon": -76.80},
        ]

        count = 0
        updated = 0
        for p in ports:
            port, created = Port.objects.update_or_create(
                name_en=p['name_en'],
                defaults={
                    'name_zh': p['name_zh'],
                    'country_en': p['country_en'],
                    'country_zh': p['country_zh'],
                    'latitude': p['lat'],
                    'longitude': p['lon']
                }
            )
            if created:
                count += 1
            else:
                updated += 1
                
        self.stdout.write(self.style.SUCCESS(f'Successfully added {count} new ports and updated {updated} existing ports.'))
