# Generated by Django 4.2.17 on 2026-02-13 02:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('crew', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobListing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('title', models.CharField(max_length=200, verbose_name='Job Title')),
                ('ship_type', models.CharField(choices=[('BULK', 'Bulk Carrier'), ('CONTAINER', 'Container Ship'), ('TANKER', 'Tanker'), ('GENERAL', 'General Cargo'), ('OTHER', 'Other')], default='BULK', max_length=20, verbose_name='Ship Type')),
                ('salary_range', models.CharField(help_text='e.g. $3000-$5000', max_length=100, verbose_name='Salary Range')),
                ('contract_duration', models.CharField(help_text='e.g. 6 months', max_length=100, verbose_name='Contract Duration')),
                ('requirements', models.TextField(blank=True, verbose_name='Requirements')),
                ('description', models.TextField(blank=True, verbose_name='Job Description')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('view_count', models.PositiveIntegerField(default=0, verbose_name='View Count')),
                ('employer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_listings', to=settings.AUTH_USER_MODEL, verbose_name='Employer')),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='listings', to='crew.jobposition', verbose_name='Position')),
            ],
            options={
                'verbose_name': 'Job Listing',
                'verbose_name_plural': 'Job Listings',
                'ordering': ['-created_at'],
            },
        ),
    ]
