# Generated by Django 4.2.17 on 2026-02-12 10:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('market', '0015_shiplisting_contact_count_shiplisting_view_count'),
    ]

    operations = [
        migrations.CreateModel(
            name='CargoRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cargo_type', models.CharField(choices=[('BULK', 'Bulk Cargo'), ('GENERAL', 'General Cargo'), ('CONTAINER', 'Container'), ('LIQUID', 'Liquid Cargo')], max_length=20, verbose_name='Cargo Type')),
                ('weight', models.FloatField(help_text='Estimated weight in tons', verbose_name='Weight (Tons)')),
                ('origin', models.CharField(max_length=100, verbose_name='Origin')),
                ('destination', models.CharField(max_length=100, verbose_name='Destination')),
                ('loading_date', models.DateField(verbose_name='Loading Date')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('MATCHED', 'Matched'), ('CLOSED', 'Closed')], default='OPEN', max_length=20, verbose_name='Status')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cargo_requests', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MatchResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.FloatField(help_text='0.0 to 1.0', verbose_name='Match Score')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_viewed', models.BooleanField(default=False)),
                ('cargo_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches', to='hymart_matching.cargorequest')),
                ('ship_listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cargo_matches', to='market.shiplisting')),
            ],
            options={
                'ordering': ['-score'],
            },
        ),
    ]
