# Generated by Django 4.2.17 on 2026-02-12 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hymart_matching', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cargorequest',
            name='max_draft',
            field=models.FloatField(blank=True, help_text='Port restriction for draft', null=True, verbose_name='Max Draft (m)'),
        ),
        migrations.AddField(
            model_name='cargorequest',
            name='volume',
            field=models.FloatField(blank=True, help_text='Estimated volume in cubic meters', null=True, verbose_name='Volume (CBM)'),
        ),
    ]
