# Generated by Django 4.2.17 on 2026-02-18 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hymart_matching', '0002_cargorequest_max_draft_cargorequest_volume'),
    ]

    operations = [
        migrations.AddField(
            model_name='cargorequest',
            name='draft_tolerance_percent',
            field=models.FloatField(blank=True, null=True, verbose_name='Draft Tolerance (%)'),
        ),
        migrations.AddField(
            model_name='cargorequest',
            name='dwt_tolerance_percent',
            field=models.FloatField(blank=True, null=True, verbose_name='DWT Tolerance (%)'),
        ),
    ]
