# Generated by Django 4.2.17 on 2026-02-19 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hymart_matching', '0003_cargorequest_draft_tolerance_percent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='matchresult',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
