# Generated by Django 4.2.17 on 2026-03-03 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hymart_matching', '0004_matchresult_is_deleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='cargorequest',
            name='unique_id',
            field=models.CharField(blank=True, editable=False, max_length=30, null=True, unique=True, verbose_name='Unique ID'),
        ),
    ]
