# Generated by Django 4.2.17 on 2026-02-17 09:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('store', '0006_product_listing_status'),
        ('services', '0005_servicelisting_listing_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='优惠券代码')),
                ('title', models.CharField(max_length=200, verbose_name='优惠券标题')),
                ('type', models.CharField(choices=[('FIXED', '固定金额'), ('PERCENTAGE', '百分比折扣'), ('FREE_SHIPPING', '免运费')], default='FIXED', max_length=20, verbose_name='类型')),
                ('value', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='优惠值')),
                ('min_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='最低消费金额')),
                ('valid_from', models.DateTimeField(verbose_name='生效时间')),
                ('valid_until', models.DateTimeField(verbose_name='过期时间')),
                ('total_quantity', models.PositiveIntegerField(default=0, verbose_name='总数量（0表示不限）')),
                ('used_quantity', models.PositiveIntegerField(default=0, verbose_name='已使用数量')),
                ('is_global', models.BooleanField(default=True, verbose_name='全场通用')),
                ('status', models.CharField(choices=[('ACTIVE', '有效'), ('EXPIRED', '已过期'), ('DISABLED', '已禁用')], default='ACTIVE', max_length=20, verbose_name='状态')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('applicable_categories', models.ManyToManyField(blank=True, to='store.category', verbose_name='适用分类')),
                ('applicable_products', models.ManyToManyField(blank=True, to='store.product', verbose_name='适用商品')),
                ('applicable_services', models.ManyToManyField(blank=True, to='services.servicelisting', verbose_name='适用服务')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
            ],
            options={
                'verbose_name': '优惠券',
                'verbose_name_plural': '优惠券',
            },
        ),
        migrations.CreateModel(
            name='UserCoupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('UNUSED', '未使用'), ('USED', '已使用'), ('EXPIRED', '已过期')], default='UNUSED', max_length=20, verbose_name='状态')),
                ('used_at', models.DateTimeField(blank=True, null=True, verbose_name='使用时间')),
                ('order_id', models.PositiveIntegerField(blank=True, null=True, verbose_name='订单ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='领取时间')),
                ('coupon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_coupons', to='market.coupon', verbose_name='优惠券')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_coupons', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '用户优惠券',
                'verbose_name_plural': '用户优惠券',
                'unique_together': {('user', 'coupon')},
            },
        ),
    ]
