# Generated by Django 4.2.17 on 2026-02-06 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Port',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_en', models.CharField(max_length=100, unique=True, verbose_name='Port Name (EN)')),
                ('name_zh', models.CharField(blank=True, max_length=100, verbose_name='Port Name (ZH)')),
                ('country_en', models.CharField(max_length=100, verbose_name='Country (EN)')),
                ('country_zh', models.CharField(blank=True, max_length=100, verbose_name='Country (ZH)')),
                ('latitude', models.FloatField(verbose_name='Latitude')),
                ('longitude', models.FloatField(verbose_name='Longitude')),
            ],
            options={
                'verbose_name': 'Port',
                'verbose_name_plural': 'Port Library',
                'ordering': ['name_en'],
            },
        ),
    ]
