# Generated by Django 4.2.17 on 2026-02-06 02:36

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BunkerPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now, verbose_name='Date')),
                ('fuel_type', models.CharField(choices=[('VLSFO', 'VLSFO (0.5%)'), ('LSMGO', 'LSMGO (0.1%)'), ('IFO380', 'IFO 380'), ('MGO', 'MGO')], max_length=10, verbose_name='Fuel Type')),
                ('price', models.DecimalField(decimal_places=2, help_text='USD/MT or CNY/MT', max_digits=10, verbose_name='Price')),
                ('currency', models.CharField(choices=[('USD', 'USD'), ('CNY', 'CNY')], default='USD', max_length=3, verbose_name='Currency')),
                ('change', models.DecimalField(decimal_places=2, default=0, help_text='Change from previous day', max_digits=10, verbose_name='Change')),
                ('source', models.CharField(blank=True, max_length=100, verbose_name='Source')),
                ('port', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bunker_prices', to='tools.port', verbose_name='Port')),
            ],
            options={
                'verbose_name': 'Bunker Price',
                'verbose_name_plural': 'Bunker Prices',
                'ordering': ['-date', 'port__name_en'],
                'unique_together': {('port', 'date', 'fuel_type')},
            },
        ),
    ]
