# Generated by Django 4.2.17 on 2026-02-06 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0002_bunkerprice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bunkerprice',
            name='fuel_type',
            field=models.CharField(choices=[('VLSFO', 'VLSFO (0.5%)'), ('LSMGO', 'LSMGO (0.1%)'), ('IFO380', 'IFO 380'), ('MGO', 'MGO'), ('RME180', 'RME 180'), ('DIESEL0', '0# Diesel')], max_length=10, verbose_name='Fuel Type'),
        ),
    ]
