# Generated by Django 4.2.17 on 2026-02-06 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0003_alter_bunkerprice_fuel_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContractTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('category', models.CharField(choices=[('SNP', 'Sale & Purchase'), ('CP', 'Charter Party')], max_length=10, verbose_name='Category')),
                ('scope', models.CharField(choices=[('DOMESTIC', 'Domestic (China)'), ('INTERNATIONAL', 'International')], max_length=20, verbose_name='Scope')),
                ('sub_type', models.CharField(choices=[('SNP_GEN', 'General S&P'), ('TC', 'Time Charter'), ('BB', 'Bareboat Charter'), ('VC', 'Voyage Charter')], max_length=20, verbose_name='Type')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('file', models.FileField(blank=True, null=True, upload_to='contract_templates/', verbose_name='Template File')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Contract Template',
                'verbose_name_plural': 'Contract Templates',
                'ordering': ['category', 'scope', 'sub_type'],
            },
        ),
    ]
